import { mkdtemp, readFile, rm, stat } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from 'path';
import execa from 'execa';
import { Job } from 'bullmq';
import { DataSource, Repository } from 'typeorm';
import storageConfig from '../../config/storage.config';
import { StorageService } from '../../storage/storage.service';
import { User } from '../../users/entities/user.entity';
import { Channel } from '../../channels/entities/channel.entity';
import {
  cleanAllTables,
  createTestDataSource,
} from '../../test/create-test-data-source';
import { Video, VideoStatus } from '../entities/video.entity';
import { VideoProcessingProcessor } from './video-processing.processor';

const ALL_ENTITIES = [User, Channel, Video];

// ffmpeg over the fixture + a DB round-trip + MinIO I/O comfortably exceed the
// 5s Jest default.
jest.setTimeout(30_000);

/** A minimal Job stub; the `updateProgress` mock is read back off `job`. */
function fakeJob(videoId: string): Job<{ videoId: string }> {
  return {
    data: { videoId },
    updateProgress: jest.fn().mockResolvedValue(undefined),
  } as unknown as Job<{ videoId: string }>;
}

describe('VideoProcessingProcessor (integration)', () => {
  let dataSource: DataSource;
  let videoRepository: Repository<Video>;
  let channelRepository: Repository<Channel>;
  let userRepository: Repository<User>;
  let storage: StorageService;
  let processor: VideoProcessingProcessor;
  let fixtureBuffer: Buffer;
  let workdir: string;

  beforeAll(async () => {
    dataSource = createTestDataSource(ALL_ENTITIES);
    await dataSource.initialize();
    videoRepository = dataSource.getRepository(Video);
    channelRepository = dataSource.getRepository(Channel);
    userRepository = dataSource.getRepository(User);

    storage = new StorageService(storageConfig());
    processor = new VideoProcessingProcessor(videoRepository, storage);

    // A tiny, valid MP4 generated by ffmpeg's synthetic test source.
    workdir = await mkdtemp(join(tmpdir(), 'proc-fixture-'));
    const fixturePath = join(workdir, 'fixture.mp4');
    await execa('ffmpeg', [
      '-y',
      '-f',
      'lavfi',
      '-i',
      'testsrc=duration=1:size=320x240:rate=10',
      '-pix_fmt',
      'yuv420p',
      fixturePath,
    ]);
    fixtureBuffer = await readFile(fixturePath);
  });

  afterAll(async () => {
    await rm(workdir, { recursive: true, force: true });
    await dataSource.destroy();
  });

  beforeEach(async () => {
    await cleanAllTables(dataSource);
  });

  let seedCounter = 0;
  async function seedVideo(
    status: VideoStatus,
    sourceBytes: Buffer,
  ): Promise<Video> {
    seedCounter += 1;
    const user = await userRepository.save(
      userRepository.create({
        email: `proc${seedCounter}@example.com`,
        password: 'hashed',
      }),
    );
    const channel = await channelRepository.save(
      channelRepository.create({
        name: 'Owner',
        nickname: `owner${seedCounter}`,
        user_id: user.id,
      }),
    );
    const publicId = `proc${seedCounter}src`;
    const storageKey = `videos/${publicId}/source`;
    await storage.putObject(storageKey, sourceBytes, 'video/mp4');
    return videoRepository.save(
      videoRepository.create({
        public_id: publicId,
        channel_id: channel.id,
        status,
        storage_key: storageKey,
      }),
    );
  }

  it('extracts duration + metadata, generates a thumbnail, and transitions to ready', async () => {
    const video = await seedVideo(VideoStatus.PROCESSING, fixtureBuffer);
    const job = fakeJob(video.id);
    const updateProgress = job.updateProgress as jest.Mock;

    await processor.process(job);

    const persisted = await videoRepository.findOneOrFail({
      where: { id: video.id },
    });
    expect(persisted.status).toBe(VideoStatus.READY);
    expect(persisted.duration_seconds).toBeGreaterThanOrEqual(1);
    expect(persisted.metadata).toBeTruthy();
    expect(persisted.metadata).toHaveProperty('format');
    expect(persisted.thumbnail_key).toBe(
      `videos/${video.public_id}/thumbnail.jpg`,
    );
    expect(persisted.processed_at).toBeInstanceOf(Date);

    // Progress is reported and reaches 100.
    expect(updateProgress).toHaveBeenCalledWith(100);
    expect(updateProgress.mock.calls.length).toBeGreaterThan(1);

    // The thumbnail was actually uploaded to storage.
    const outDir = await mkdtemp(join(tmpdir(), 'proc-thumb-'));
    const thumbPath = join(outDir, 'thumb.jpg');
    await storage.downloadToFile(persisted.thumbnail_key!, thumbPath);
    expect((await stat(thumbPath)).size).toBeGreaterThan(0);
    await rm(outDir, { recursive: true, force: true });
  });

  it('marks the video failed on a corrupt source without crashing the worker', async () => {
    const video = await seedVideo(
      VideoStatus.PROCESSING,
      Buffer.from('not a real video'),
    );
    const job = fakeJob(video.id);

    // process() rejects on the corrupt source (ffprobe fails)...
    await expect(processor.process(job)).rejects.toBeDefined();

    // ...and the `failed` worker event drives the terminal transition.
    await processor.onFailed(job);

    const persisted = await videoRepository.findOneOrFail({
      where: { id: video.id },
    });
    expect(persisted.status).toBe(VideoStatus.FAILED);
  });

  it('is idempotent — re-running over the same source yields the same final state', async () => {
    const video = await seedVideo(VideoStatus.PROCESSING, fixtureBuffer);

    await processor.process(fakeJob(video.id));
    const first = await videoRepository.findOneOrFail({
      where: { id: video.id },
    });

    await processor.process(fakeJob(video.id));
    const second = await videoRepository.findOneOrFail({
      where: { id: video.id },
    });

    expect(second.status).toBe(VideoStatus.READY);
    expect(second.duration_seconds).toBe(first.duration_seconds);
    expect(second.thumbnail_key).toBe(first.thumbnail_key);
  });
});
